### ISSUE TITLE
Run tests on all supported platforms

### ISSUE THREAD

**Issue by KrysKruk** [Neft-io/neft#28]
All internal modules tests should be tested on each supported platform: node, browser, ios and android using generated bundle files.

##### TODO
 - [X] Create neft bundles on Travis
 - [x] Integrate Travis with SauceLabs
 - [ ] Run tests on bundle files
 - [ ] ... to be continued
